product_category/shop_with_elasticsearch/shop_with_elasticsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/',include('store.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

product_category/shop_with_elasticsearch/store/urls.py
from django.urls import path
from . import views

app_name='store'

urlpatterns=[
    path('',views.home_page_view,name="index"),
    path('register/',views.register_view,name="register"),
    path("login/",views.login,name="login"),
    path("logout/",views.logout,name="logout"),
    path("detail-<int:id>/",views.show_detail,name="detail"),
    path("search_dish",views.search_dish,name="search_dish"),
]

product_category/shop_with_elasticsearch/store/models.py
from django.db import models
#from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=30,blank=True, null=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Cuisine(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=100,blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    image = models.ImageField(upload_to='products') #upload_to='topics/%Y/%m/%d/'

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title

    @staticmethod
    def get_all_Cuisines():
        return Cuisine.objects.all()

    @staticmethod
    def get_all_Cuisines_by_category_id(category_id):
        if category_id:
            return Cuisine.objects.filter(category=category_id)
        else:
            return Cuisine.get_all_Cuisines()

product_category/shop_with_elasticsearch/store/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User,auth
from .models import Cuisine, Category
from .documents import CuisineDocument
from django.contrib.auth.decorators import login_required

# Create your views here.
def home_page_view(request):

    categories=Category.objects.all()
    products = None
    category_id=request.GET.get('category')

    if category_id:
        products=Cuisine.get_all_Cuisines_by_category_id(category_id)
    else:
        products=Cuisine.get_all_Cuisines()

    data={}
    data['products']=products
    data['categories']=categories
    return render(request, 'store/index.html',data)

def search_dish(request):
    if request.method == 'POST':
        search=request.POST.get('searched')
        #products=Cuisine.objects.filter(name__icontains = search)
        # using elastic search

        if search:
            products= CuisineDocument.search().query('match',title=search)


        return render(request, 'store/search.html', {'search' : search, 'products':products})
    else:
        return render(request, 'store/search.html', {})



def register_view(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 == password2:

            if User.objects.filter(username=username).exists():
                messages.info(request, "username already taken")
            elif User.objects.filter(email=email).exists():
                messages.info(request, "email already taken")
            else:
                user=User.objects.create_user(username=username,password=password1,email=email,first_name=first_name,last_name=last_name)
                user.save()
                return redirect("store:login")
        else:
            messages.info(request,"password not matching")
            return redirect("store:register")
        return redirect("/store")
    else:
        return render(request, 'store/register.html')

def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']

        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            messages.success(request, 'you are logged in')
            return redirect("/store")
        else:
            messages.warning(request, 'you are not authorized for it')
            return redirect("store:login")
    else:

        return render(request,'store/login.html')

def logout(request):
    auth.logout(request)
    return redirect("/store")


def show_detail(request,id):
    product=Cuisine.objects.get(id=id)
    #product = get_object_or_404(Product,pk=id)
    return render(request, "store/show_detail.html", {"product": product})

product_category/shop_with_elasticsearch/templates/footer.html
<footer class="tm-footer text-center">
  <p>Copyright &copy; 2020 Simple House

        | Design: <a rel="nofollow" href="https://templatemo.com">TemplateMo</a></p>
</footer>

product_category/shop_with_elasticsearch/templates/header.html
{% load static %}

<div class="container">
<!-- Top box -->
  <!-- Logo & Site Name -->
  <div class="placeholder">
    <div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'img/simple-house-01.jpg' %}">
      <div class="tm-header">
        <div class="row tm-header-inner">
          <div class="col-md-6 col-12">
            <img src="{% static 'img/simple-house-logo.png' %}"" alt="Logo" class="tm-site-logo" />
            <div class="tm-site-text-box">
              <h1 class="tm-site-title">Simple House</h1>
            </div>
          </div>
          <nav class="col-md-6 col-12 tm-nav">
            <ul class="tm-nav-ul">
              <li class="tm-nav-li"><a href="{% url 'store:index' %}" class="tm-nav-link active">Home</a></li>

              {% if user.is_authenticated%}
              <h2>Hello, {{user.username}}</h2>
              <li class="tm-nav-li"><a href="{% url 'store:logout' %}" class="tm-nav-link">Logout</a></li>
              {% else %}
                <li class="tm-nav-li"><a href="{% url 'store:register' %}" class="tm-nav-link">Register</a></li>
                <li class="tm-nav-li"><a href="{% url 'store:login' %}" class="tm-nav-link">Login</a></li>
              {% endif %}
              </ul>
            </nav>

            <br>
          <nav>
            <ul>
              <div class="container" style="width:250px;">
					<form method="POST" action="{% url 'store:search_dish' %}">
						{% csrf_token %}
						<input type="search" class="form-control me-2" placeholder="Search" aria-label="Search" name="searched">
						<button class="btn btn-outline-secondary" type="submit">Search</button>
					</form>
                </div>

            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

product_category/shop_with_elasticsearch/templates/noodle.html
{% load static %}

<div id="tm-gallery-page-noodle" class="tm-gallery-page hidden">
  
  <article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
    <figure>
      {% for n in noodle %}
      <img src="{{MEDIA_ROOT}}.{{n.image.url}}" alt="Image" class="img tm-gallery-img" />
      <figcaption>
        <h4 class="tm-gallery-title">{{n.title}}</h4>
        <p class="tm-gallery-description">{{n.description}}/p>
        <p class="tm-gallery-price">${{n.price}}</p>
      </figcaption>
      {% endfor %}
    </figure>
  </article>
</div>

product_category/shop_with_elasticsearch/templates/pizza.html
{% load static %}

<div class="container-fluid">
	<div class="row tm-gallery">
		<div id="tm-gallery-page-pizza" class="tm-gallery-page">
			<article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
				<figure>
					{% for product in products %}
								{% if user.is_authenticated%}
					           <a href="{% url 'store:detail' product.id %}">{% endif %}
								   <img class="imgchange" src="{% if request.resolver_match.url_name == 'search_dish' %}{{product.image}}{% else %}{{product.imageURL}}{% endif %}" alt="{{product.image}}" class="img-fluid tm-gallery-img"></a>

<!--								<div class="card-body>-->
<!--								{{product.image}}-->
<!--								<h5 class="card title" >{{product.title}}</h5>-->
<!--								<h3>Rs{{product.price}}</h3>-->
<!--								<small>{{product.description}}</small>-->
<!--					<small><strong>{{product.category.name}}</strong></small>-->
<!--								-->
<!--							</div>-->
						<figcaption>
				          	<p class="tm-gallery-title">{{product.title}}</p>
							<p class="tm-gallery-price">Rs {{product.price}}</p>
				          	<p class="tm-gallery-description">{{product.description}}</p><br>

				        </figcaption>
					{% endfor %}
				</figure>
			</article>
		</div>
	</div>
</div>
<!--

				        {% for item in products %}
				       	<img src="{% if request.resolver_match.url_name == "search_dish" %}{{item.image}}{% else %}{{item.imageURL}}{% endif %}" alt="{% if request.resolver_match.url_name == "search_dish" %}{{item.image}}{% else %}{{item.imageURL}}{% endif %}" class="img tm-gallery-img" />

				        {% endfor %}



	 -->

product_category/shop_with_elasticsearch/templates/salad.html
{% load static %}

<div id="tm-gallery-page-salad" class="tm-gallery-page hidden">
  <article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
    <figure>
      {% for s in salad %}
      <a href="{% url 'app:show_detail_salad' s.pk %}"><img src="{{MEDIA_URL}}.{{s.image.url}}" alt="Image" class="img tm-gallery-img" /></a>
      <figcaption>
        <h4 class="tm-gallery-title">{{s.title}}</h4>
        <p class="tm-gallery-description">{{s.description}}</p>
        <p class="tm-gallery-price">${{s.price}}</p>
      </figcaption>
      {% endfor %}
    </figure>
  </article>
</div>

product_category/shop_with_elasticsearch/templates/store/index.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Simple House Template</title>
		<style media="screen">
			.imgchange{
				height:300px;
				width:250px;
			}
		</style>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400" rel="stylesheet" />
	<link href="{% static 'css/templatemo-style.css' %}" rel="stylesheet" />
</head>
<body>
		<main>
			{% include 'header.html'%}
			<header class="row tm-welcome-section">
				<h2 class="col-12 text-center tm-section-title">Welcome to Simple House</h2>
			</header>
			<div class="container" >
 			{%if messages %}

			 {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible alert-fixed" role="alert" >
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  {{ message }}
                </div>
              {% endfor %}

			{% endif %}

</div>

			<div class="tm-paging-links">
				<nav>
						<ul>

							{% for category in categories %}
									<li class="tm-paging-item"><a href="/store/?category={{category.id}}" class="list-group-item list-group-item-action">{{category.name}}</a></li>
							{% endfor %}

						</ul>

				</nav>

			</div>
			{% block upper %}

			{% endblock %}
			<br>


			<!-- Gallery -->

			{% include 'pizza.html' %}

				<!-- <div class="row tm-gallery">
				  <div id="tm-gallery-page-pizza" class="tm-gallery-page">

				    <article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
				      <figure>
				        {% for item in products %}
				       	<img src="{% if request.resolver_match.url_name == "search_dish" %}{{item.image}}{% else %}{{item.imageURL}}{% endif %}" alt="{% if request.resolver_match.url_name == "search_dish" %}{{item.image}}{% else %}{{item.imageURL}}{% endif %}" class="img tm-gallery-img" />
				        <figcaption>
				          <h4 class="tm-gallery-title">{{item.name}}</h4>
				          <p class="tm-gallery-description">{{item.description}}</p>
				          <p class="tm-gallery-price">${{item.price}}</p>
				        </figcaption>
				        {% endfor %}
				      </figure>
				    </article>
				</div>
			</div> -->



				<!-- gallery page 1 -->


				<!-- gallery page 2 -->

				 <!-- gallery page 2 -->

				<!-- gallery page 3 -->

				<!-- gallery page 3 -->
			<!-- </div> -->

		</main>



	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/parallax.min.js' %}"></script>
	<script>
		$(document).ready(function(){
			// Handle click on paging links
			$('.tm-paging-link').click(function(e){
				e.preventDefault();

				var page = $(this).text().toLowerCase();
				$('.tm-gallery-page').addClass('hidden');
				$('#tm-gallery-page-' + page).removeClass('hidden');
				$('.tm-paging-link').removeClass('active');
				$(this).addClass("active");
			});
		});
	</script>
</body>
</html>

product_category/shop_with_elasticsearch/templates/store/login.html
{% extends "store/register.html" %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <style>
    .tm-nav-link{
        color:white;
    }
    </style>
  </head>
  <body>

  <a href="{% url 'store:index' %}" class="tm-nav-link active">Home</a></li>

    {% block form %}

    <form class="" action="" method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="username"><br>
      <input type="password" name="password" placeholder="password">
      <input type="submit" name="" value="submit">
    </form>
    {% endblock %}
    <div class="container" >
<!--     {%if messages %}-->

<!--           {% for message in messages %}-->
<!--                    <div class="alert alert-{{ message.tags }} alert-dismissible alert-fixed" role="alert" >-->
<!--                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>-->
<!--                      {{ message }}-->
<!--                    </div>-->
<!--                  {% endfor %}-->

<!--    {% endif %}-->

  </body>
</html>

product_category/shop_with_elasticsearch/templates/store/register.html
{%load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
    <style>

    body, html {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    display:table;
}
body {
    display:table-cell;
    vertical-align:middle;
    color:white;
}
form {

    display:table;/* shrinks to fit content */
    margin:auto;
    border
}
input[type=text], input[type=password] {
 width: 100%;
 padding: 15px;
 margin: 5px 0 22px 0;
 border: none;
 background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
 background-color: #ddd;
 outline: none;
}

.form_login{
  border:50px;
}


    </style>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body style="background-image: url('{% static 'img/simple-house-01.jpg' %}')">

    <div class="parallax-window" data-parallax="scroll" >
      <div class="container">
        <nav class="col-md-6 col-12 tm-nav">
          <ul class="tm-nav-ul">
            <li class="tm-nav-li"><a href="{% url 'store:index' %}" class="tm-nav-link active">Home</a></li>
          </ul>
        </nav>
        {% block form%}

      <form class="form_login" action="" method="post" height='300'>
        {% csrf_token %}

        <div class="form-group ">
          <label for="fname" class="form-text text-muted">Enter first name</label>
          <input type="text" class="form-control" id="fname" aria-describedby="emailHelp" name="first_name" placeholder="Enter first name">
        </div>
        <div class="form-group ">
          <label for="lname" class="form-text text-muted">Enter last name</label>
          <input type="text" class="form-control" id="lname" aria-describedby="emailHelp" name='last_name' placeholder="Enter last name">
        </div>
        <div class="form-group ">
          <label for="uname" class="form-text text-muted">Enter username</label>
          <input type="text" class="form-control" id="uname" aria-describedby="emailHelp" name="username" placeholder="Enter username">
        </div>
          <div class="form-group form-text text-muted">
            <label for="exampleInputEmail1" class="text-muted">Email address</label>
            <input type="email" class="form-control " id="exampleInputEmail1" aria-describedby="emailHelp" name="email" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
          </div>
          <div class="form-group">
            <label for="Password1" class="text-muted">Password</label>
            <input type="password" class="form-control" id="Password1" name="password1" placeholder="Password">
          </div>
          <div class="form-group">
            <label for="Password2" class="text-muted">Password again</label>
            <input type="password" class="form-control" id="Password2" name="password2" placeholder="Confirm password">
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>

      </form>
{% endblock %}
      <div class="container" >
       {%if messages %}

      			 {% for message in messages %}
                      <div class="alert alert-{{ message.tags }} alert-dismissible alert-fixed" role="alert" >
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        {{ message }}
                      </div>
                    {% endfor %}

      {% endif %}
    </div>
    </div>
  </body>
</html>

product_category/shop_with_elasticsearch/templates/store/search.html
{% extends 'store/index.html' %}
{% load static %}
{% block upper %}
<center>
<!--    {% if search %}-->
    <h1>You searched for....{{ search }}</h1>
<!--    {% for product in products %}-->

<!--    {% empty %}-->

    <h1>No search for {{search }} found</h1>
    {% endfor %}
<!--    {% else %}-->
    <h1>Sorry...</h1>
<!--    {% endif %}-->

</center>
{% endblock %}

product_category/shop_with_elasticsearch/templates/store/show_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Detail page</title>
    <style media="screen">
    body{
      background: #c3dbca;
    }
    </style>

  </head>
  <body>
    {% include 'header.html'%}
      <h1>{{product.name}}</h1>
      <h2>{{product.description}}</h2>
      <h3>${{product.price}}</h3>
      <img src="{{ product.imageURL }}" height="300px" width="500px">


  </body>
</html>