new_admin_django/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('website/', include('website.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new_admin_django/ecommerce/myapp/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path

from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    # path('register/',views.register, name = 'register'),
    path('logout/', views.logoutUser, name='logout'),

    # user management
    path('users/', views.UserList, name='UserList'),
    path('users/user_add', views.UserAdd, name='UserAdd'),
    path('users/user_update/<int:id>', views.UserUpdate, name='UserUpdate'),
    path('users/user_delete/<int:id>', views.UserDelete, name='UserDelete'),
    # path('users/user_change', views.UserChange, name='UserChange'),
    # path('users/user_update/<int:id>/user_change_psw', views.UserChangePsw, name='UserChangePsw'),

    path('group/',views.group_list,name='group'),
    path('group/add/',views.group_select,name='GroupAdd'),

    # categories
    path('category/', views.category_list, name='category_list'),
    path('category/add/', views.new_category, name='add_category'),
    # path('category/<int:pk>/', views.detail_category, name='detail_category'),
    path('category/edit/<int:pk>/', views.edit_category, name='edit_category'),
    path('category/delete/<int:pk>', views.delete_category, name='delete_category'),

    path('product/', views.product_list, name='ProductList'),
    path('product/add/', views.add_new_product, name='ProductAdd'),
    path('product/edit/<int:id>/', views.edit_product, name='ProductEdit'),
    path('product/delete/<int:id>', views.delete_product, name='ProductDelete'),

    path('productAttribute/', views.Product_Attribute, name='ProductAttribute'),
    path('productAttribute/add/', views.Product_Attribute_Add, name='ProductAttributeAdd'),
    path('productAttribute/edit/<int:id>/', views.Product_Attribute_Edit, name='ProductAttributeEdit'),
    path('productAttribute/delete/<int:id>/', views.Product_Attribute_Delete, name='ProductAttributeDelete'),

    path('productAttributeValue/', views.Product_Attribute_Value, name='ProductAttributeValue'),
    path('productAttributeValue/add/', views.Product_Attribute_Value_Add, name='ProductAttributeValueAdd'),
    path('productAttributeValue/edit/<int:id>/', views.Product_Attribute_Value_Edit, name='ProductAttributeValueEdit'),
    path('productAttributeValue/delete/<int:id>/', views.Product_Attribute_Value_Delete,
         name='ProductAttributeValueDelete'),

    path('banner/', views.banner_list, name='BannerList'),
    path('banner/add', views.new_banner, name='BannerAdd'),
    path('banner/edit/<int:id>', views.edit_banner, name='BannerEdit'),
    path('banner/delete/<int:id>', views.delete_banner, name='BannerDelete')

]

new_admin_django/ecommerce/website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('register/', views.register_view, name='register_view'),
    path('category_item/<int:id>/', views.category_item, name='category_item'),
    path('product_detail/<int:id>/', views.ProductDetail, name='ProductDetail'),
    path('add_to_wishlist/<int:id>/',views.add_to_wishlist,name='add_to_wishlist'),
]

new_admin_django/ecommerce/website/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.models import User, Group, AnonymousUser
# from django.contrib.auth import get_user_model

from django import template
from django.conf import settings
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from django.core.paginator import Paginator

from django.contrib import messages

from myapp.models import User, Banner, Categories, Product, ProductImage, UserWishlist

from myapp.forms import RegisterForm


# Create your views here.
def home(request):
    banner = Banner.objects.filter(status='Active')
    categories = Categories.objects.filter(status=True)
    products=Product.objects.filter(status=True)
    product_images=ProductImage.objects.filter(product__is_featured__icontains=True)
    #product_images=ProductImage.product.all()
    #Product.objects.filter(attribute_values__value_option_id=2).filter(attribute_values__value_option_id=6)


    paginator=Paginator(products,6)
    products=paginator.page(1)

    return render(request, 'website/home.html', {'banners': banner,
                                                 'categories': categories,
                                                 'products':products,
                                                 'product_images':product_images})


# def register_view(request):
#     if request.method == 'POST':
    #     first_name = request.POST.get('first_name')
    #     last_name = request.POST.get('last_name')
    #     # username = request.POST.get('username_register')
    #     email = request.POST.get('email')
    #     password1 = request.POST.get('password1')
    #     password2 = request.POST.get('password2')
    #
    #     if password1 == password2:
    #         # if User.objects.filter(username=username).exists():
    #         #     messages.info(request, "username already taken")
    #         if User.objects.filter(email=email).exists():
    #             messages.info(request, "email already taken")
    #         else:
    #             user = User.objects.create_user(password=password1, email=email, first_name=first_name,
    #                                             last_name=last_name)
    #             user.save()
    #             login(request, user)
    #             messages.success(request, "You are successfully registered")
    #             return redirect("website:home")
    #     else:
    #         messages.info(request, "password not matching")
    #         return redirect("website:register_view")
    #     return redirect("website:home")
    # else:
    #     return render(request, 'website/register.html')

def register_view(request):
    if request.method == 'POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            # email = form.cleaned_data['email']
            # password = form.cleaned_data['password1']
            form = form.save()
            # default_group = Group.objects.get(name='customer')
            # form.groups.add(default_group)
            form.save()
            messages.success(request, 'Registered was successfully created!')
            return redirect('website:login_view')
    else:
        form = RegisterForm()
    return render(request,'website/login.html',{'form':form})


def login_view(request):
    if request.method == 'POST':
        email = request.POST.get('email_login')
        password = request.POST.get('password')
        # no need
        valuenext = request.POST.get('next')

        user = authenticate(request,email=email, password=password)
        if user is not None and valuenext == '':
            login(request, user)
            messages.success(request, 'you are logged in')
            return redirect('website:home')
        elif user is not None and valuenext != '':
            login(request, user)
            return redirect(valuenext)
        else:
            messages.warning(request, 'email or password is incorrect.')
            return redirect('website:login_view')
    else:
        return render(request, 'website/login.html')

@login_required(login_url='website:login_view')
def logout_view(request):
    logout(request)
    return redirect('website:home')

def category_item(request,id):
    categories=Categories.objects.all()
    products=Product.objects.filter(product__product_categories__id=id).order_by('-created_date')
    product_images=ProductImage.objects.filter(product__product_categories__id=id).order_by('-created_date')
    paginator = Paginator(products, 4)
    products = paginator.page(1)

    id = id
    return render(request, 'website/category_item.html',
                  {'products': products, 'categories': categories, 'id': id, 'product_images': product_images})

def ProductDetail(request, id):
    product = Product.objects.get(id=id)
    categories = Categories.objects.all()
    product_images = ProductImage.objects.filter(product=product)
    # for product_image in product_images:
    # print(product_images.image_name)

    return render(request, 'website/product_detail.html',
                  {'product_images': product_images, 'product': product, 'categories': categories})

@login_required(login_url='website:login_view')
def add_to_wishlist(request,id):

   product = get_object_or_404(Product,id=id)

   wished_item = UserWishlist.objects.get_or_create(product=product,user=request.user)

   messages.info(request,'The item was added to your wishlist')
   return redirect('website:home')

new_admin_django/ecommerce/templates/website/footer_website.html
{% load static %}
<footer id="footer"><!--Footer-->
<!--		<div class="footer-top">-->
<!--			<div class="container">-->
<!--				<div class="row">-->
<!--					<div class="col-sm-2">-->
<!--						<div class="companyinfo">-->
<!--							<h2><span>e</span>-shopper</h2>-->
<!--							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>-->
<!--						</div>-->
<!--					</div>-->
<!--					<div class="col-sm-7">-->
<!--						<div class="col-sm-3">-->
<!--							<div class="video-gallery text-center">-->
<!--								<a href="#">-->
<!--									<div class="iframe-img">-->
<!--										<img src="{% static 'images/home/iframe1.png' %}" alt="" />-->
<!--									</div>-->
<!--									<div class="overlay-icon">-->
<!--										<i class="fa fa-play-circle-o"></i>-->
<!--									</div>-->
<!--								</a>-->
<!--								<p>Circle of Hands</p>-->
<!--								<h2>24 DEC 2014</h2>-->
<!--							</div>-->
<!--						</div>-->

<!--						<div class="col-sm-3">-->
<!--							<div class="video-gallery text-center">-->
<!--								<a href="#">-->
<!--									<div class="iframe-img">-->
<!--										<img src="{% static 'images/home/iframe2.png' %}" alt="" />-->
<!--									</div>-->
<!--									<div class="overlay-icon">-->
<!--										<i class="fa fa-play-circle-o"></i>-->
<!--									</div>-->
<!--								</a>-->
<!--								<p>Circle of Hands</p>-->
<!--								<h2>24 DEC 2014</h2>-->
<!--							</div>-->
<!--						</div>-->

<!--						<div class="col-sm-3">-->
<!--							<div class="video-gallery text-center">-->
<!--								<a href="#">-->
<!--									<div class="iframe-img">-->
<!--										<img src="{% static 'images/home/iframe3.png' %}" alt="" />-->
<!--									</div>-->
<!--									<div class="overlay-icon">-->
<!--										<i class="fa fa-play-circle-o"></i>-->
<!--									</div>-->
<!--								</a>-->
<!--								<p>Circle of Hands</p>-->
<!--								<h2>24 DEC 2014</h2>-->
<!--							</div>-->
<!--						</div>-->

<!--						<div class="col-sm-3">-->
<!--							<div class="video-gallery text-center">-->
<!--								<a href="#">-->
<!--									<div class="iframe-img">-->
<!--										<img src="{% static 'images/home/iframe4.png' %}" alt="" />-->
<!--									</div>-->
<!--									<div class="overlay-icon">-->
<!--										<i class="fa fa-play-circle-o"></i>-->
<!--									</div>-->
<!--								</a>-->
<!--								<p>Circle of Hands</p>-->
<!--								<h2>24 DEC 2014</h2>-->
<!--							</div>-->
<!--						</div>-->
<!--					</div>-->
<!--					<div class="col-sm-3">-->
<!--						<div class="address">-->
<!--							<img src="{% static 'images/home/map.png' %}" alt="" />-->
<!--							<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!--		</div>-->

		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
								<li><a href="#">Change Location</a></li>
								<li><a href="#">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Womens</a></li>
								<li><a href="#">Gift Cards</a></li>
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
								<li><a href="#">Billing System</a></li>
								<li><a href="#">Ticket System</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">Store Location</a></li>
								<li><a href="#">Affillate Program</a></li>
								<li><a href="#">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">{% csrf_token %}
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
					<p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
				</div>
			</div>
		</div>

	</footer><!--/Footer-->

new_admin_django/ecommerce/templates/website/header_website.html
{% load static %}

<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->

		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="{% url 'website:home' %}"><img src="{% static 'images/home/logo.png' %}" alt="" /></a>
						</div>
<!--						<div class="btn-group pull-right">-->
<!--							<div class="btn-group">-->
<!--								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">-->
<!--									USA-->
<!--									<span class="caret"></span>-->
<!--								</button>-->
<!--								<ul class="dropdown-menu">-->
<!--									<li><a href="#">Canada</a></li>-->
<!--									<li><a href="#">UK</a></li>-->
<!--								</ul>-->
<!--							</div>-->

<!--							<div class="btn-group">-->
<!--								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">-->
<!--									DOLLAR-->
<!--									<span class="caret"></span>-->
<!--								</button>-->
<!--								<ul class="dropdown-menu">-->
<!--									<li><a href="#">Canadian Dollar</a></li>-->
<!--									<li><a href="#">Pound</a></li>-->
<!--								</ul>-->
<!--							</div>-->
<!--						</div>-->
					</div>

					{% block nav-header %}
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
<!--								<li><a href="#"><i class="fa fa-user"></i> Account</a></li>-->
<!--								<li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>-->
<!--								<li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>-->
<!--								<li><a href="cart.html"><i class="fa fa-shopping-cart"></i> Cart</a></li>-->

<!--									{% if request.user.is_authenticated%}-->
<!--								  <small>Hello, {{user.email}}</small>-->
<!--								  <li class="tm-nav-li"><a href="{% url 'website:logout_view' %}" class="tm-nav-link">Logout</a></li>-->
<!--								  {% else %}-->
<!--									<li><a href="{% url 'website:login_view' %}"><i class="fa fa-lock"></i>Login</a></li>-->
<!--									<li><a href="{% url 'website:register_view' %}"><i class="fa fa-lock"></i>Register</a></li>-->
<!--								  {% endif %}-->

								{% if request.user.is_authenticated%}
`								<li>
										<div class="btn-group">
											<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
												<i class="fa fa-user"></i> Account
												<span class="caret"></span>
											</button>
											<ul class="dropdown-menu">
												<li><a href="{% url 'website:logout_view' %}"><i class="fa fa-lock"></i> Logout</a></li>

											</ul>
									    </div>
									</li>
								{% else %}
								<li><a href="{% url 'website:login_view' %}"><i class="fa fa-lock"></i> Login/Register </a></li>
								{% endif %}
							</ul>
						</div>
					</div>
					{% endblock %}
				</div>
			</div>
		</div><!--/header-middle-->

		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
<!--						<div class="navbar-header">-->
<!--							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">-->
<!--								<span class="sr-only">Toggle navigation</span>-->
<!--								<span class="icon-bar"></span>-->
<!--								<span class="icon-bar"></span>-->
<!--								<span class="icon-bar"></span>-->
<!--							</button>-->
<!--						</div>-->
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
<!--								<li><a href="{% url 'website:home'%}" class="active">Home</a></li>-->
								<li><a href="{% url 'website:home' %}" class="{% if request.resolver_match.url_name == "home"%}
									active{% endif %}">Home</a></li>
								<li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
										{% if request.user.is_authenticated %}
                                        <li><a href="shop.html">Products</a></li>
										<li><a href="product-details.html">Product Details</a></li>
										<li><a href="checkout.html">Checkout</a></li>
										<li><a href="cart.html">Cart</a></li>
										<li><a href="login.html">Login</a></li>
										{% endif %}
                                    </ul>
                                </li>
<!--								<li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>-->
<!--                                    <ul role="menu" class="sub-menu">-->
<!--                                        <li><a href="blog.html">Blog List</a></li>-->
<!--										<li><a href="blog-single.html">Blog Single</a></li>-->
<!--                                    </ul>-->
<!--                                </li>-->
<!--								<li><a href="404.html">404</a></li>-->
<!--								<li><a href="contact-us.html">Contact</a></li>-->
							</ul>
						</div>
					</div>
<!--					<div class="col-sm-3">-->
<!--						<div class="search_box pull-right">-->
<!--							<input type="text" placeholder="Search"/>-->
<!--						</div>-->
<!--					</div>-->
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->

new_admin_django/ecommerce/templates/website/home.html
{% extends 'website/base_website.html' %}
{% load static %}

{% block title %}
{{block.super}}
{% endblock %}

{% block wrapper %}

	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							{% for banner in banners%}
							<li data-target="#slider-carousel" data-slide-to="{{ forloop.counter }}" {% if forloop.first %}class="active" {% endif %}></li>
							{% endfor %}
						</ol>

						<div class="carousel-inner">
							{% for banner in banners %}
							<div class="item {% if forloop.first %}active{% endif %}">

<!--style="max-width:484px;max-height:425px;min-width:484px;min-height:425px;"-->
									<img src="{{banner.file_path}}" class="img-responsive" style="max-width:1500px;max-height:500px;min-width:1000px;min-height:300px;" alt="" />
							</div>

							{% endfor %}

						</div>


						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>


				</div>
			</div>
		</div>
	</section><!--/slider-->



<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							{% for category in categories %}	
							<div class="panel panel-default">
								{% if category.parent is not None %}
								
									<div class="panel-heading">
										<h4 class="panel-title">
											<a href="{% url 'website:category_item' category.id %}" class="category-call" data-category="{{category.id}}">
												{% for child in categories %}
												{% if child.parent == category %}
												{% ifchanged %}
												<a data-toggle="collapse" data-parent="#accordian" href="#{{category.name}}">
													<span class="badge pull-right"><i class="fa fa-plus"></i></span>
													{% endifchanged %}
													{% endif %}
													{% endfor %}
													{{category.name}}
												</a>
											</a>
<!--											<a data-toggle="collapse" data-parent="#accordian" href="#sportswear">-->
<!--												<span class="badge pull-right"><i class="fa fa-plus"></i></span>-->
<!--												Sportswear-->
<!--											</a>-->
										</h4>
									</div>
								<div id="{{ category.name }}" class="panel-collapse collapse">
								<div class="panel-body">
									<ul>

										{% for child in categories %}
										{% if child.parent == category %}

										<li><a href="{% url 'website:category_item' category.id %}" class="category-call" data-category="{{ child.id }}">{{ child.name }} </a></li>
										{% endif%}
										{% endfor %}

										<li><a href="{% url 'website:category_item' category.id %}" class="category-call" data-category="{{ category.id }}"> All {{ category.name }} </a></li>
									</ul>
								</div>
							</div>
								{% endif %}
								</div>
							{% endfor %}
							</div><!--/category-products-->
						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well text-center">
								 <input type="text" class="span2 price-filter" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
<!--								<button type="button" class="btn btn-primary price-filter-button">filter</button>-->
							</div>
						</div><!--/price-range-->

<!--									<div id="sportswear" class="panel-collapse collapse">-->
<!--										<div class="panel-body">-->
<!--											<ul>-->
<!--												<li><a href="#">Nike </a></li>-->
<!--												<li><a href="#">Under Armour </a></li>-->
<!--												<li><a href="#">Adidas </a></li>-->
<!--												<li><a href="#">Puma</a></li>-->
<!--												<li><a href="#">ASICS </a></li>-->
<!--											</ul>-->
<!--										</div>-->
<!--									</div>-->

					</div>

				</div>
				<div class="col-sm-9 padding-right">
					<div class="features_items"  id="category-new-data" ><!--features_items-->

						<h2 class="title text-center">Feature items</h2>

						{% for product in products %}
						<div class="col-sm-4">
								<div class="product-image-wrapper">
									<div class="single-products">
											<div class="productinfo text-center">
												category: {{ product.product_categories.all|join:',' }}


												<img src="{{product.productimage.first.image_name.url }}" alt="" style="max-width:255.48px;min-width:255.48px;max-height:200px;min-height:210px;" />
												<p>{{ product.productmeta.title }}</p>
												{% if product.special_price_test %}

														<h2 ><span style="text-decoration: line-through; color:black;">${{product.price}}</span>${{product.special_price}}</h2>

												{% else %}

														<h2>${{product.price}}</h2>

												{% endif %}
												<p>{{product.name}}</p>
												<a href="" class="btn btn-default add-to-cart"  data-action ="add" data-product = '{{ product.id }}'  ><i class="fa fa-shopping-cart"></i>Add to cart</a>
											</div>

											<div class="product-overlay">

												<a href="{% url 'website:ProductDetail' product.id %}" >
													<div class="overlay-content">

												{% if product.special_price_test %}
														<h2 ><span style="text-decoration: line-through; color:black;">${{product.price}}</span>${{product.special_price}}</h2>

												{% else %}

														<h2>${{product.price}}</h2>

												{% endif %}

													<p>{{product.long_description}}</p>
													<a href="" class="btn btn-default add-to-cart"  data-action ="add" data-product = '{{ product.id }}'   ><i class="fa fa-shopping-cart"></i>Add to cart</a>
													</div>
												</a>
											</div>
										{% if product.special_price_test %}
										<img src="static/Eshopper/images/home/sale.png" class="new" alt="">
										{% endif %}
										{% if product.is_new %}
										<img src="static/Eshopper/images/home/new.png" class="new" alt="">
										{% endif %}

<!--										<img src="static/Eshopper/images/home/new.png" class="new" alt="">-->
									</div>

									<div class="choose">
										<ul class="nav nav-pills nav-justified">
											<li><a href="{% url 'website:add_to_wishlist' product.id %}" class="add-to-whishlist" data-action="add" data-product = '{{ product.id }}' ><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										</ul>
									</div>
								</div>

							</div>
						{% endfor %}

	<div class="load_data">

						</div>

					</div>
					<div class="load_data_message">
						<a class="btn btn-default button-message">load more</a>
					</div>

<!-------------------------       upto here       	-------------------------------------------------------------------------->

				</div>
			</div>
		</div>
	</section>

{% endblock %}

new_admin_django/ecommerce/templates/website/product_detail.html
{% extends 'website/base_website.html' %}
{% load static %}

{% block title %}
{{block.super}}
{% endblock %}

{% block wrapper %}
{% if products %}
{% for pro in product %}
  {{pro.price}}
{% endfor %}
{% endif %}
{% endblock %}