simple_django_project/mysite/app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='app'

urlpatterns = [
    path('',views.home_page_view,name="index"),
    path('app/register/',views.register_view,name="register"),
    path("app/login/",views.login,name="login"),
    path("app/logout/",views.logout,name="logout"),
    path("app/<int:image_id>/",views.show_detail,name="show_detail"),
    path("app/<int:pk>/",views.show_detail_salad,name="show_detail_salad")
]
# to grab the integer of the id
urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

simple_django_project/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
#from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
    #path('',views.home_page_view,name="index"),
    #path('register/',views.register_view,name="register")
]

simple_django_project/mysite/app/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    title=models.CharField(max_length=20)
    description=models.TextField()
    price=models.IntegerField()
    image=models.ImageField(upload_to='pics')

class Salad(models.Model):
    title=models.CharField(max_length=20)
    description=models.TextField()
    price=models.IntegerField()
    image=models.ImageField(upload_to='pics')

class Noodle(models.Model):
    title=models.CharField(max_length=20)
    description=models.TextField()
    price=models.IntegerField()
    image=models.ImageField(upload_to='pics')

simple_django_project/mysite/app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User,auth
from app.models import Pizza,Salad,Noodle

# Create your views here.
def home_page_view(request):
    pizza=Pizza.objects.all()
    salad=Salad.objects.all()
    noodle=Noodle.objects.all()

    return render(request,'app/index.html',{'pizza':pizza,'salad':salad,'noodle':noodle})

def register_view(request):
    if request.method=='POST':
        first_name=request.POST['first_name']
        last_name=request.POST['last_name']
        username=request.POST['username']
        email=request.POST['email']
        password1=request.POST['password1']
        password2=request.POST['password2']

        if password1==password2:

            if User.objects.filter(username=username).exists():
                messages.info(request,"username already taken")
            elif User.objects.filter(email=email).exists():
                messages.info(request,"email already taken")
            else:
                user=User.objects.create_user(username=username,password=password1,email=email,first_name=first_name,last_name=last_name)
                user.save()
                return redirect("app:login")
        else:
            messages.info(request,"password not matching")
            return redirect("app:register")
        return redirect('/')
    else:
        return render(request, 'app/register.html')

def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']

        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            messages.success(request, 'you are logged in')
            return redirect("/")
        else:
            messages.warning(request, 'you are not authorized for it')
            return redirect("app:login")
    else:

        return render(request,'app/login.html')

def logout(request):
    auth.logout(request)
    return redirect("/")

def show_detail(request,image_id):
    images = get_object_or_404(Pizza,pk=image_id)
    return render(request,"app/show.html",{"images": images})

def show_detail_salad(request,pk):
    images_1 = get_object_or_404(Salad,pk=pk)
    return render(request,"app/show_detail_salad.html",{"images_1": images_1})

simple_django_project/mysite/templates/header.html
{% load static %}

<div class="container">
<!-- Top box -->
  <!-- Logo & Site Name -->
  <div class="placeholder">
    <div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'img/simple-house-01.jpg' %}">
      <div class="tm-header">
        <div class="row tm-header-inner">
          <div class="col-md-6 col-12">
            <img src="{% static 'img/simple-house-logo.png' %}"" alt="Logo" class="tm-site-logo" />
            <div class="tm-site-text-box">
              <h1 class="tm-site-title">Simple House</h1>
            </div>
          </div>
          <nav class="col-md-6 col-12 tm-nav">
            <ul class="tm-nav-ul">
              <li class="tm-nav-li"><a href="{% url 'app:index' %}" class="tm-nav-link active">Home</a></li>

              {% if user.is_authenticated%}
              <h2>Hello, {{user.username}}</h2>
              <li class="tm-nav-li"><a href="{% url 'app:logout' %}" class="tm-nav-link">Logout</a></li>
              {% else %}
                <li class="tm-nav-li"><a href="{% url 'app:register' %}" class="tm-nav-link">Register</a></li>
                <li class="tm-nav-li"><a href="{% url 'app:login' %}" class="tm-nav-link">Login</a></li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

simple_django_project/mysite/templates/pizza.html
{% load static %}

<div id="tm-gallery-page-pizza" class="tm-gallery-page">

  <article class="col-lg-3 col-md-4 col-sm-6 col-12 tm-gallery-item">
    <figure>
      {% for p in pizza %}
      <a href="{% url 'app:show_detail' p.id %}"><img src="{{MEDIA_URL}}{{p.image.url}}" alt="Image" class="img tm-gallery-img" /></a>
      <figcaption>
        <h4 class="tm-gallery-title">{{p.title}}</h4>
        <p class="tm-gallery-description">{{p.description}}</p>
        <p class="tm-gallery-price">${{p.price}}</p>
      </figcaption>
      {% endfor %}
    </figure>
  </article>
</div>